[package]
name = "zksnark_coursework"
version = "0.1.0"
authors = ["Artyom"]
edition = "2021"

[dependencies]
nova-snark = "0.41.0"
ff = "0.13.0"
flate2 = "1.0.35"
rand = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
